@WebApi_HostAddress = http://localhost:5105

GET {{WebApi_HostAddress}}/api/contacts
Accept: application/json

###
GET http://localhost:5105/api/contacts/26ee1377-8471-4623-a99d-62256634832c
Accept: application/json

###
POST {{WebApi_HostAddress}}/api/contacts
Content-Type: application/json

{
  "firstName": "Adam",
  "lastName" : "Nowak",
  "Email": "adam@wsei.edu.pl",
  "phone": "48 123 456 789"
}


###
POST {{WebApi_HostAddress}}/api/contacts
Content-Type: application/json

{
  "firstName": "Adam",
  "lastName" : "Nowak"
}

###
POST {{WebApi_HostAddress}}/api/contacts
Content-Type: application/json

{
  "firstName": "Antoni",
  "lastName" : "Kowalski",
  "email": "antek@wsei.edu.pl",
  "phone": "48 123 456 333",
  "address": {
    "street": "Krowoderska 10",
    "city": "Krakow",
    "postalCode": "31-145",
    "country": "Poland"
  }
}

###
PUT http://localhost:5105/api/contacts/fa4c7c6a-102a-45bc-842f-678c72c97bfe
Content-Type: application/json

{
  "firstName": "Antonina",
  "lastName": "Kowalski-Nowak",
  "email": "antonina@wsei.edu.pl",
  "phone": "48 999 000 111",
  "gender": 1,
  "id": "fa4c7c6a-102a-45bc-842f-678c72c97bfe"
}

###
POST {{WebApi_HostAddress}}/api/contacts/ffa044c3-2c26-4478-9438-7ce9db7b4d74/notes
Content-Type: application/json

{
  "content": "New note"
}
###
GET {{WebApi_HostAddress}}/api/contacts/34e32c3c-4255-4cb7-ab69-55e7bcf50b88/notes
Content-Type: application/json
