@WebApi_HostAddress = http://localhost:5105

GET {{WebApi_HostAddress}}/api/contacts
Accept: application/json

###
GET http://localhost:5105/api/contacts/26ee1377-8471-4623-a99d-62256634832c
Accept: application/json

###
POST {{WebApi_HostAddress}}/api/contacts
Content-Type: application/json

{
  "firstName": "Adam",
  "lastName" : "Nowak",
  "Email": "adam@wsei.edu.pl",
  "phone": "48 123 456 789"
}


###
POST {{WebApi_HostAddress}}/api/contacts
Content-Type: application/json

{
  "firstName": "Adam",
  "lastName" : "Nowak"
}

###
POST {{WebApi_HostAddress}}/api/contacts
Content-Type: application/json

{
  "firstName": "Antoni",
  "lastName" : "Kowalski",
  "email": "antek@wsei.edu.pl",
  "phone": "48 123 456 333",
  "address": {
    "street": "Krowoderska 10",
    "city": "Krakow",
    "postalCode": "31-145",
    "country": "Poland"
  }
}

###
PUT http://localhost:5105/api/contacts/fa4c7c6a-102a-45bc-842f-678c72c97bfe
Content-Type: application/json

{
  "firstName": "Antonina",
  "lastName": "Kowalski-Nowak",
  "email": "antonina@wsei.edu.pl",
  "phone": "48 999 000 111",
  "gender": 1,
  "id": "fa4c7c6a-102a-45bc-842f-678c72c97bfe"
}

###
POST {{WebApi_HostAddress}}/api/contacts/a3acddb3-a2cf-4d0c-9437-4a135e363c61/notes
Content-Type: application/json

{
  "content": "New note"
}
###
GET {{WebApi_HostAddress}}/api/contacts/a3acddb3-a2cf-4d0c-9437-4a135e363c61/notes
Content-Type: application/json

###
DELETE {{WebApi_HostAddress}}/api/contacts/a3acddb3-a2cf-4d0c-9437-4a135e363c61/notes/4b7c77d0-42f6-477b-9dbd-0ca86e3ad6f6
Content-Type: application/json


###
POST {{WebApi_HostAddress}}/api/auth/login
Content-Type: application/json

{
  "email": "admin@wsei.edu.pl",
  "password": "Admin123!"
}

###
# Oczekiwane: 401 Unauthorized (bledne haslo)
POST {{WebApi_HostAddress}}/api/auth/login
Content-Type: application/json

{
  "email": "admin@wsei.edu.pl",
  "password": "zle_haslo"
}

###
POST {{WebApi_HostAddress}}/api/auth/login
Content-Type: application/json
	
{
  "email": "jan.kowalski@crm.pl",
  "password": "Manager@123!"
}

###
# 1) Odśwież tokeny (wklej wartości z poprzedniego 200 OK)
POST {{WebApi_HostAddress}}/api/auth/refresh
Content-Type: application/json

{
  "accessToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6ImFhYWFhYWFhLWFhYWEtYWFhYS1hYWFhLWFhYWFhYWFhYWFhYSIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2VtYWlsYWRkcmVzcyI6ImFkbWluQHdzZWkuZWR1LnBsIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvZ2l2ZW5uYW1lIjoiSmFuIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvc3VybmFtZSI6Iktvd2Fsc2tpIiwiZGVwYXJ0bWVudCI6IkFkbWluaXN0cmFjamEiLCJzdGF0dXMiOiJBY3RpdmUiLCJqdGkiOiIyZTNiMjE0MS05OTYzLTRkNTMtYjViMC0zYjJmMDM2MzQzZDciLCJpYXQiOiIxNzc2ODA3MjA3IiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiQWRtaW5pc3RyYXRvciIsIm5iZiI6MTc3NjgwNzIwNywiZXhwIjoxNzc2ODEwODA3LCJpc3MiOiJJZGVpc0NybUFwaSIsImF1ZCI6IkNybUNsaWVudCJ9.85cp-h2PJl4PJeNX6gIhJvDIVVMt76LH8ecgovXg1tk",
  "refreshToken": "0+geQQudb9kgUvdltF27129IBaf6GKa2+PAaCGZMyi394LkCtAGjnyF6pXVJVpN+1GpbNfQ5wrgVV/g/vKD4pQ=="
}

###
# 2) Dane zalogowanego użytkownika (wklej accessToken)
GET {{WebApi_HostAddress}}/api/auth/me
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6ImFhYWFhYWFhLWFhYWEtYWFhYS1hYWFhLWFhYWFhYWFhYWFhYSIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2VtYWlsYWRkcmVzcyI6ImFkbWluQHdzZWkuZWR1LnBsIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvZ2l2ZW5uYW1lIjoiSmFuIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvc3VybmFtZSI6Iktvd2Fsc2tpIiwiZGVwYXJ0bWVudCI6IkFkbWluaXN0cmFjamEiLCJzdGF0dXMiOiJBY3RpdmUiLCJqdGkiOiJmZTM1NjVkMC1lZGEwLTRhMTQtYTcxYy05ZjgyYjkxNDdlZTYiLCJpYXQiOiIxNzc2ODA3NjQ2IiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiQWRtaW5pc3RyYXRvciIsIm5iZiI6MTc3NjgwNzY0NiwiZXhwIjoxNzc2ODExMjQ2LCJpc3MiOiJJZGVpc0NybUFwaSIsImF1ZCI6IkNybUNsaWVudCJ9.GP0nIQrI8_AVoeOvvsLnEofeob_n1UoEtqV9cj3g740


###
# 3) Wylogowanie (odwołanie refresh tokenu)
POST {{WebApi_HostAddress}}/api/auth/revoke
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6ImFhYWFhYWFhLWFhYWEtYWFhYS1hYWFhLWFhYWFhYWFhYWFhYSIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2VtYWlsYWRkcmVzcyI6ImFkbWluQHdzZWkuZWR1LnBsIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvZ2l2ZW5uYW1lIjoiSmFuIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvc3VybmFtZSI6Iktvd2Fsc2tpIiwiZGVwYXJ0bWVudCI6IkFkbWluaXN0cmFjamEiLCJzdGF0dXMiOiJBY3RpdmUiLCJqdGkiOiJmZTM1NjVkMC1lZGEwLTRhMTQtYTcxYy05ZjgyYjkxNDdlZTYiLCJpYXQiOiIxNzc2ODA3NjQ2IiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiQWRtaW5pc3RyYXRvciIsIm5iZiI6MTc3NjgwNzY0NiwiZXhwIjoxNzc2ODExMjQ2LCJpc3MiOiJJZGVpc0NybUFwaSIsImF1ZCI6IkNybUNsaWVudCJ9.GP0nIQrI8_AVoeOvvsLnEofeob_n1UoEtqV9cj3g740

"DHxx8W0mG/R99EbhGseqcDhuYtkvhgJyuO5RXIehooSKt+Dic/Yq8cNMz4R78Ezlx47c7SeTmH16mBYLtd2dJw=="
###
# 4) Kontakty (wymaga tokenu przez politykę ReadOnlyAccess)
GET {{WebApi_HostAddress}}/api/contacts
Accept: application/json
Authorization: Bearer {{accessToken}}

